name: neuraleasel
title: NeuralEasel
base: core18 
version: '0.1' 
license: MIT
summary: Open-source DeepDream generator
description: |
  Easily generate your own deep dream images from a GUI.
icon: snap/gui/icon.png
compression: lzo
confinement: strict

apps:
  neuraleasel: 
    adapter: full
    command: desktop-launch $SNAP/bin/neuraleasel
    environment:
      DISABLE_WAYLAND: 1
    plugs:
      - desktop
      - desktop-legacy
      - opengl
      - wayland
      - x11
       
# From snapcraft-desktop-helpers
# https://github.com/ubuntu/snapcraft-desktop-helpers
parts:
  desktop-qt5:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    plugin: make
    make-parameters: ["FLAVOR=qt5"]
    build-packages:
      - build-essential
      - qtbase5-dev
      - dpkg-dev
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5 # for loading icon themes which are svg
      - try: [appmenu-qt5] # not available on core18
      - locales-all
      - xdg-user-dirs
      - fcitx-frontend-qt5

  neuraleasel:
    after: [desktop-qt5]
    plugin: python
    python-version: python3
    source: .
    # Based on ericoporto/pyqthelloworld
    # https://github.com/ericoporto/pyqthelloworld
    build-packages:
      - python3
      - python3-pyqt5
      - execstack
    stage-packages:
      - python3
      - python3-pyqt5
      - libc-bin
      - locales

